export const liga7 = `
GassanBr x Helior44
llTk87ll x 13JCruel13
Rsscoach x MuraKamiGu
AlekaSabbag x TomDSantos
13JCruel13 x HHazuka
llTk87ll x ZuziaMao
TomDSantos x vib
AlekaSabbag x Helior44
ZuziaMao x MuraKamiGu
HHazuka x c4i00
Helior44 x Rsscoach
13JCruel13 x TgoSorelli
TomDSantos x c4i00
Rsscoach x llTk87ll
c4i00 x TgoSorelli
ZuziaMao x AlekaSabbag
HHazuka x vib
TomDSantos x MuraKamiGu
Rsscoach x vib
c4i00 x MuraKamiGu
AlekaSabbag x TgoSorelli
ZuziaMao x 13JCruel13
HHazuka x llTk87ll
TgoSorelli x GassanBr
13JCruel13 x Helior44
MuraKamiGu x vib
TomDSantos x GassanBr
vib x GassanBr
c4i00 x Helior44
HHazuka x AlekaSabbag
Helior44 x llTk87ll
13JCruel13 x Rsscoach
Rsscoach x GassanBr
vib x ZuziaMao
c4i00 x GassanBr
HHazuka x TomDSantos
GassanBr x llTk87ll
13JCruel13 x AlekaSabbag
TomDSantos x llTk87ll
c4i00 x ZuziaMao
ZuziaMao x Helior44
HHazuka x Rsscoach
13JCruel13 x vib
Rsscoach x AlekaSabbag
vib x TgoSorelli
c4i00 x llTk87ll
AlekaSabbag x MuraKamiGu
ZuziaMao x GassanBr
HHazuka x MuraKamiGu
VicTavares x Mamazzaro
SinGoLfaiRe x RegininhaKawaii
Guilram91 x Tiringstorm34
Diogenest x Pamps2805
Pamps2805 x Brabrinha
Tiringstorm34 x Teresak1
Teresak1 x rikardolima
Brabrinha x MauColella
VicTavares x mi88akz
RegininhaKawaii x QueenBelinha
rikardolima x Allanlima04
MauColella x WallanLima16
Guilram91 x JimbobAzul
Diogenest x SinGoLfaiRe
Pamps2805 x Mamazzaro
Teresak1 x MaikTheOne
VicTavares x QueenBelinha
SinGoLfaiRe x Allanlima04
rikardolima x RegininhaKawaii
QueenBelinha x MaikTheOne
MauColella x MaikTheOne
Guilram91 x Brabrinha
Diogenest x JimbobAzul
Allanlima04 x Mamazzaro
Pamps2805 x Tiringstorm34
Tiringstorm34 x WallanLima16
Teresak1 x JimbobAzul
QueenBelinha x Mamazzaro
MauColella x mi88akz
Guilram91 x mi88akz
Diogenest x rikardolima
Allanlima04 x RegininhaKawaii
Pamps2805 x MaikTheOne
Teresak1 x WallanLima16
Mamazzaro x WallanLima16
rikardolima x JimbobAzul
QueenBelinha x Tiringstorm34
MauColella x JimbobAzul
Guilram91 x VicTavares
Diogenest x WallanLima16
Allanlima04 x VicTavares
Pamps2805 x mi88akz
Tiringstorm34 x Brabrinha
Teresak1 x mi88akz
mi88akz x RegininhaKawaii
Mamazzaro x Brabrinha
VicTavares x SinGoLfaiRe
WallanLima16 x RegininhaKawaii
QueenBelinha x SinGoLfaiRe
Guilram91 x SinGoLfaiRe
Diogenest x Brabrinha
Pamps2805 x Allanlima04
Brabrinha x rikardolima
Mamazzaro x MauColella
VicTavares x Teresak1
SinGoLfaiRe x mi88akz
MauColella x Tiringstorm34
Guilram91 x WallanLima16
Allanlima04 x JimbobAzul
Tiringstorm34 x rikardolima
Mamazzaro x RegininhaKawaii
VicTavares x Diogenest
WallanLima16 x JimbobAzul
SinGoLfaiRe x Pamps2805
rikardolima x QueenBelinha
QueenBelinha x mi88akz
MauColella x RegininhaKawaii
Guilram91 x MaikTheOne
Diogenest x Teresak1
BinhoZica01 x Douglete011
Marcelo69 x Gsaito87
Marcelo69 x Douglete011
Manfrim11 x Gsaito87
Manfrim11 x Douglete011
Manfrim11 x BinhoZica01
RaulAV1 x BinhoZica01
RaulAV1 x Marcelo69
GinoLucca x Manfrim11
GinoLucca x Gsaito87
GinoLucca x BinhoZica01
GinoLucca x RaulAV1
GinoLucca x Marcelo69
Oftentimes7 x RaulAV1
Oftentimes7 x GinoLucca
Oftentimes7 x BinhoZica01
Oftentimes7 x Marcelo69
Oftentimes7 x Manfrim11
Oftentimes7 x Douglete011
Oftentimes7 x Gsaito87
Atilajg x Gsaito87
Atilajg x Manfrim11
Atilajg x Douglete011
Atilajg x RaulAV1
Atilajg x BinhoZica01
Atilajg x GinoLucca
mestreDohko x Gsaito87
mestreDohko x Marcelo69
mestreDohko x GinoLucca
mestreDohko x RaulAV1
mestreDohko x Douglete011
mestreDohko x BinhoZica01
VanEdipo x BinhoZica01
VanEdipo x Marcelo69
VanEdipo x Gsaito87
VanEdipo x Manfrim11
VanEdipo x Atilajg
MasterLineYr x Atilajg
MasterLineYr x Marcelo69
MasterLineYr x Douglete011
MasterLineYr x Manfrim11
MasterLineYr x Gsaito87
TgoSorelli x TomDSantos
TgoSorelli x MuraKamiGu
TgoSorelli x Helior44
VanEdipo x Douglete011
VanEdipo x mestreDohko
VanEdipo x RaulAV1
MasterLineYr x RaulAV1
MasterLineYr x Oftentimes7
MasterLineYr x mestreDohko
MaikTheOne x Allanlima04
MaikTheOne x Brabrinha
MaikTheOne x JimbobAzul
Patyeiko x BarbaKetchum
PedrinhoGamarra x GuiMi19
genosfull x Yeyas81
genosfull x CopperKid
genosfull x LuksBertolli
DGKetchum1 x GuiMi19
DGKetchum1 x CopperKid
TsuSetoguchi x RedZoom
TsuSetoguchi x Didideluca
TsuSetoguchi x PedrinhoGamarra
TsuSetoguchi x Patyeiko
TsuSetoguchi x genosfull
TsuSetoguchi x CopperKid
123CatBond x Yeyas81
123CatBond x LuksBertolli
123CatBond x GuiMi19
qdeza x RedZoom
qdeza x PedrinhoGamarra
qdeza x LuksBertolli
qdeza x DGKetchum1
qdeza x GuiMi19
qdeza x 123CatBond
didisantista x BarbaKetchum
didisantista x Yeyas81
didisantista x DGKetchum1
didisantista x genosfull
didisantista x TsuSetoguchi
Juracrav x Didideluca
Juracrav x BarbaKetchum
Juracrav x RedZoom
Juracrav x LuksBertolli
Juracrav x CopperKid
Juracrav x DGKetchum1
Juracrav x didisantista
Juracrav x qdeza
Fgsanfre x Didideluca
Fgsanfre x Yeyas81
Fgsanfre x PedrinhoGamarra
Fgsanfre x BarbaKetchum
Fgsanfre x CopperKid
Fgsanfre x genosfull
Fgsanfre x didisantista
marcioljunior x Patyeiko
marcioljunior x Yeyas81
marcioljunior x GuiMi19
marcioljunior x DGKetchum1
marcioljunior x BarbaKetchum
marcioljunior x 123CatBond
brankinho40 x RedZoom
brankinho40 x Didideluca
brankinho40 x LuksBertolli
brankinho40 x BarbaKetchum
brankinho40 x CopperKid
brankinho40 x DGKetchum1
brankinho40 x Yeyas81
HigashiRicardo x PedrinhoGamarra
HigashiRicardo x Didideluca
HigashiRicardo x RedZoom
HigashiRicardo x marcioljunior
HigashiRicardo x GuiMi19
HigashiRicardo x genosfull
HigashiRicardo x 123CatBond
HigashiRicardo x BarbaKetchum
DavidFirmin0 x Yeyas81
DavidFirmin0 x TsuSetoguchi
DavidFirmin0 x RedZoom
DavidFirmin0 x PedrinhoGamarra
DavidFirmin0 x GuiMi19
DavidFirmin0 x Didideluca
DavidFirmin0 x DGKetchum1
DavidFirmin0 x BarbaKetchum
Cecmartins x RedZoom
Cecmartins x qdeza
Cecmartins x PedrinhoGamarra
Cecmartins x marcioljunior
Cecmartins x LuksBertolli
Cecmartins x Didideluca
Cecmartins x 123CatBond
Winiciuslb1810 x Patyeiko
Winiciuslb1810 x didisantista
Winiciuslb1810 x LuksBertolli
Winiciuslb1810 x Yeyas81
Winiciuslb1810 x GuiMi19
Winiciuslb1810 x Didideluca
Winiciuslb1810 x CopperKid
Rafa25Albertin x RedZoom
Rafa25Albertin x PedrinhoGamarra
Rafa25Albertin x Patyeiko
Rafa25Albertin x Winiciuslb1810
Rafa25Albertin x LuksBertolli
Rafa25Albertin x CopperKid
Rafa25Albertin x brankinho40
Rafa25Albertin x genosfull
Patyeiko x Fgsanfre
Patyeiko x 123CatBond
Patyeiko x Cecmartins
`;
